# Chapter 5 of Python for Data Analysis

In [1]:
from pandas import Series, DataFrame
import numpy as np
import pandas as pd

In [3]:
obj = Series([4, 7, -5, 3])
print(obj.values)
print(obj.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [10]:
obj2 = Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'd'])
print(obj2['d'])
print(type(obj2.values))
print(type(obj2.index))
print(type(obj2))

d    4
d    5
dtype: int64
<class 'numpy.ndarray'>
<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.series.Series'>


In [17]:
obj3 = {'a' : 1, 'b' : 2, 'c' : 3}
obj3 = Series(obj3)
'a' in obj3 # True
1 in obj3 # False
np.in1d(1, obj3.values)

array([ True])

In [21]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}
obj5 = Series(sdata)
obj5 = Series(obj5, index=['Ohio', 'Texas', 'Bejing'])
print(obj5)
pd.isna(obj5).any()

Ohio      35000.0
Texas     71000.0
Bejing        NaN
dtype: float64


True

In [25]:
obj5.name = 'population'
obj5.index.name = 'city'
print(obj5)

city
Ohio      35000.0
Texas     71000.0
Bejing        NaN
Name: population, dtype: float64


In [32]:
test_df = {'A' : [1, 2, 3],
           'B' : [4, 6, 8],
           'C' : [5, 7, 99]}
test_df = DataFrame(test_df, index=['Beijing', 'Shanghai', 'Chongqing'])
print(test_df)

           A  B   C
Beijing    1  4   5
Shanghai   2  6   7
Chongqing  3  8  99


In [43]:
test_series = test_df.A
print(test_series)

# test_df.ix['Beijing']    discarded
print(test_df.loc['Beijing', :])
print(test_df.loc['Beijing',])
type(test_df.loc['Beijing', ['A', 'C']]) # after using .loc, it has become a Series
type(test_df.loc[['Beijing', 'Chongqing'], ['A', 'C']]) # DataFrame

Beijing      1
Shanghai     2
Chongqing    3
Name: A, dtype: int64
A    1
B    4
C    5
Name: Beijing, dtype: int64
A    1
B    4
C    5
Name: Beijing, dtype: int64


pandas.core.frame.DataFrame

In [50]:
obj6 = {'A' : {'Beijing':1, 'Shanghai':2, 'Chongqing':3}, 'B' : {'Beijing':4, 'Shanghai':6, 'Chongqing':8}}
obj6 = DataFrame(obj6)
print(obj6)
print(type(obj6.T))
print(obj6.values)

           A  B
Beijing    1  4
Shanghai   2  6
Chongqing  3  8
<class 'pandas.core.frame.DataFrame'>
[[1 4]
 [2 6]
 [3 8]]


In [65]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
print(obj2)
1 in obj2.index

obj2.index.unique()
pd.unique(obj2.index)
index.is_unique
index.unique
index.is_monotonic

0    1.5
1   -2.5
2    0.0
dtype: float64


True

In [3]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)
print(obj)
print(obj2)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64
a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64


In [8]:
frame = DataFrame(np.arange(9).reshape(3, 3), index=['Beijing', 'Shanghai', 'Chongqing'], columns=['A', 'B', 'C'])
frame.reindex(index=['Beijing', 'Shanghai', 'Chongqing', 'Tianjin'], columns=['A', 'B', 'C', 'D'])

A    B    C   D
Beijing    0.0  1.0  2.0 NaN
Shanghai   3.0  4.0  5.0 NaN
Chongqing  6.0  7.0  8.0 NaN
Tianjin    NaN  NaN  NaN NaN

In [9]:
data = DataFrame(np.arange(16).reshape(4, 4), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [19]:
print(data)
print(data[0:2])
# print(data[2])   False
data.loc['Ohio', 'one']
print(data.loc[1, 1])
data.iloc[1, 1]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7


5

In [22]:
frame = DataFrame(np.arange(12).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [25]:
f = lambda x: x.max() - x.min()
print(frame.apply(f))
print(frame.apply(f, axis=1))

b    9
d    9
e    9
dtype: int64
Utah      2
Ohio      2
Texas     2
Oregon    2
dtype: int64


In [27]:
def f(x):
    return Series([x.max(), x.min()], index=['Max', 'Min'])

frame.apply(f)
frame.apply(f, axis=1)

Max  Min
Utah      2    0
Ohio      5    3
Texas     8    6
Oregon   11    9

In [28]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    0.00   1.00   2.00
Ohio    3.00   4.00   5.00
Texas   6.00   7.00   8.00
Oregon  9.00  10.00  11.00

In [30]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [33]:
obj = Series([4, 7, -3, 2])
# obj.order() Error
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [35]:
obj = Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()
print(obj)

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64


In [37]:
obj = Series(['a', 'a', 'b', 'c'] * 4)
print(obj)
obj.describe()

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object


count     16
unique     3
top        a
freq       8
dtype: object