# 数据规整化

In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [28]:
df1 = DataFrame({'key' : ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1' : range(7)})
df2 = DataFrame({'key' : ['a', 'b', 'd'], 'data2' : range(3)})

pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [ ]:
df3 = DataFrame({'lkey' : ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1' : range(7)})
df4 = DataFrame({'rkey' : ['a', 'b', 'd'], 'data2' : range(3)})

pd.merge(df3, df4, left_on='lkey', right_on='rkey')

In [ ]:
print(pd.merge(df1, df2, how='left'))
print(pd.merge(df1, df2, how='right'))
print(pd.merge(df1, df2, how='outer'))

In [ ]:
left = DataFrame({'key1' : ['foo', 'foo', 'bar'],
                  'key2' : ['one', 'two', 'one'],
                  'lval' : [1, 2, 3]})
right = DataFrame({'key1' : ['foo', 'foo', 'bar', 'bar'],
                   'key2' : ['one', 'one', 'one', 'two'],
                   'lval' : [4, 5, 6, 7]})

pd.merge(left, right, on='key1', how='outer', suffixes=('_left', '_right'))

In [ ]:
left_df = DataFrame([[1., 2.], [3., 4.], [5., 6.]], index=['a', 
'c', 'e'], columns=['Ohio', 'Nevada'])
right_df = DataFrame([[7., 8.], [9., 10.], [11., 12.], [13., 14.]], index=['b', 'c', 'd', 'e'], columns=['Missouri', 'Alabama'])

pd.merge(left_df, right_df, how='outer', left_index=True, right_index=True)

In [ ]:
print(left_df.join(right_df, how='right'))
print(left_df.join(right_df, how='left'))

In [35]:
arr = np.arange(12).reshape((3, 4))
print(np.concatenate([arr, arr], axis=0))
print(np.concatenate([arr, arr], axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [37]:
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['f', 'g'])

joint_s = pd.concat([s1, s2, s3])
type(joint_s)

pandas.core.series.Series

In [39]:
joint_s = pd.concat([s1, s2, s3], axis=1)
print(type(joint_s))
print(joint_s)

<class 'pandas.core.frame.DataFrame'>
     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0


In [46]:
result1 = pd.concat([s1, s2, s3], keys=['one', 'two', 'three'])
print(result1)
type(result1.unstack())

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64


pandas.core.frame.DataFrame

In [48]:
result2 = pd.concat([s1, s2, s3], keys=['one', 'two', 'three'], axis=1)
print(result2)

   one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0


In [50]:
df1 = DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])
print(pd.concat([df1, df2]))
print(pd.concat([df1, df2], ignore_index=True))

          a         b         c         d
0 -0.397156  1.594142  0.827900  1.319840
1 -0.349130 -1.083904  0.211642 -0.263606
2  0.810517 -0.707759 -0.461879 -0.147731
0 -0.037172 -0.466378       NaN -0.451507
1 -0.410540 -0.350071       NaN  1.360973
          a         b         c         d
0 -0.397156  1.594142  0.827900  1.319840
1 -0.349130 -1.083904  0.211642 -0.263606
2  0.810517 -0.707759 -0.461879 -0.147731
3 -0.037172 -0.466378       NaN -0.451507
4 -0.410540 -0.350071       NaN  1.360973


In [51]:
df1 = DataFrame({'a' : [1, np.nan, 5., np.nan],
                 'b' : [np.nan, 2., np.nan, 6.],
                 'c' : range(2, 18, 4)})

df2 = DataFrame({'a' : [5., 4., np.nan, 3., 7.],
                 'b' : [np.nan, 3., 4., 6., 8.]})

df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [2]:
data = DataFrame(np.arange(6).reshape((2, 3)), index=pd.Index(['Ohio', 'Colorado'], name='state'), columns=pd.Index(['one', 'two', 'three'], name='number'))
print(data)

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5


In [5]:
result = data.stack()
print(data.stack())
print(data.stack().unstack())

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64
number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5


In [9]:
print(result.unstack(0))
print(result.unstack(1))
print(result.unstack('state'))

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5
number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5
state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5


In [11]:
s1 = Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s2 = Series([4, 5, 6], index=['c', 'd', 'e'])
data2 = pd.concat([s1, s2], keys=['one', 'two'])
print(data2)

data2_2 = pd.concat([s1, s2], axis=1, keys=['one', 'two'])
print(data2_2)

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64
   one  two
a  0.0  NaN
b  1.0  NaN
c  2.0  4.0
d  3.0  5.0
e  NaN  6.0


In [16]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [18]:
df = DataFrame({'left' : result, 'right' : result + 5}, columns=pd.Index(['left', 'right'], name='side'))
print(df)

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10


In [19]:
df.unstack('state').stack('side')

state         Colorado  Ohio
number side                 
one    left          3     0
       right         8     5
two    left          4     1
       right         9     6
three  left          5     2
       right        10     7

In [60]:
time_p1 = list(np.repeat(pd.Timestamp('1959-03-31 00:00:00'), 3))
time_p2 = list(np.repeat(pd.Timestamp('1959-06-30 00:00:00'), 3))

print(np.append(time_p1, time_p2))

ldata = DataFrame({'date' : np.append(time_p1, time_p2), 'item' : (['realgdp', 'infl', 'unemp'] * 2), 'value' : [2710.349, 0.000, 5.800, 2778.801, 2.340, 5.100]})

print(ldata)

[Timestamp('1959-03-31 00:00:00') Timestamp('1959-03-31 00:00:00')
 Timestamp('1959-03-31 00:00:00') Timestamp('1959-06-30 00:00:00')
 Timestamp('1959-06-30 00:00:00') Timestamp('1959-06-30 00:00:00')]
        date     item     value
0 1959-03-31  realgdp  2710.349
1 1959-03-31     infl     0.000
2 1959-03-31    unemp     5.800
3 1959-06-30  realgdp  2778.801
4 1959-06-30     infl     2.340
5 1959-06-30    unemp     5.100


In [66]:
# pivot wider
print(type(ldata))
pivoted = ldata.pivot('date', 'item', 'value')


DatetimeIndex(['1959-03-31', '1959-06-30'], dtype='datetime64[ns]', name='date', freq=None)

In [71]:
ldata['value2'] = np.random.randn(len(ldata))
print(len(ldata))
print(ldata.shape[1])
print(ldata)

6
4
        date     item     value    value2
0 1959-03-31  realgdp  2710.349 -0.385069
1 1959-03-31     infl     0.000  0.968437
2 1959-03-31    unemp     5.800 -1.899621
3 1959-06-30  realgdp  2778.801 -0.285930
4 1959-06-30     infl     2.340 -0.475144
5 1959-06-30    unemp     5.100 -1.292779


In [76]:
print(ldata.pivot('date', 'item', 'value'))
pivoted = ldata.pivot('date', 'item')

print(pivoted['value2', 'infl'])

item        infl   realgdp  unemp
date                             
1959-03-31  0.00  2710.349    5.8
1959-06-30  2.34  2778.801    5.1
date
1959-03-31    0.968437
1959-06-30   -0.475144
Name: (value2, infl), dtype: float64


In [80]:
print(ldata)
ldata.set_index(['date', 'item']).unstack('item')
ldata.set_index(['date', 'item']).unstack('item').value2

        date     item     value    value2
0 1959-03-31  realgdp  2710.349 -0.385069
1 1959-03-31     infl     0.000  0.968437
2 1959-03-31    unemp     5.800 -1.899621
3 1959-06-30  realgdp  2778.801 -0.285930
4 1959-06-30     infl     2.340 -0.475144
5 1959-06-30    unemp     5.100 -1.292779


item            infl   realgdp     unemp
date                                    
1959-03-31  0.968437 -0.385069 -1.899621
1959-06-30 -0.475144 -0.285930 -1.292779

In [3]:
data = DataFrame({'k1' : ['one'] * 3 + ['two'] * 4, 'k2' : [1, 1, 2, 3, 3, 4, 4]})

data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [4]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [6]:
data['v1'] = range(7)
print(data)
data.drop_duplicates(['k1'])

    k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6


k1  k2  v1
0  one   1   0
3  two   3   3

In [8]:
data.drop_duplicates(['k1', 'k2'], keep='last')
data.drop_duplicates(['k1', 'k2'], keep='first')

k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

In [26]:
data = DataFrame({'food' : ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'], 'ounces' : [4., 3., 12., 6., 7.5, 8., 3., 5., 6.]})
print(data)

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0


In [27]:
meat_to_animal = {
    'bacon' : 'pig',
    'pulled pork' : 'pig',
    'pastrami' : 'cow',
    'corned beef' : 'cow',
    'honey ham' : 'pig',
    'nova lox' : 'salmon'
}

In [25]:
print(data)
print(data['food'].map(str.lower).map(meat_to_animal))
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
print(data)

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon
0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object
          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon


In [28]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [29]:
data = Series([1, 2, 3, 4, 5, 999, -999])
data.replace([999, -999], np.nan)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
6    NaN
dtype: float64

In [30]:
data.replace([999, -999], [np.nan, 1024])

0       1.0
1       2.0
2       3.0
3       4.0
4       5.0
5       NaN
6    1024.0
dtype: float64

In [32]:
data = DataFrame(np.arange(12).reshape((3, 4)), 
                  index=['Ohio', 'Colorado', 'New York'],
                  columns=['one', 'two', 'three', 'four'])

In [34]:
data.index = data.index.map(str.upper)
print(data)

          one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11


In [35]:
data.rename(index=str.upper, columns=str.title)

One  Two  Three  Four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [36]:
ages = [20, 22, 25, 27, 21, 23, 37, 99, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
print(cats)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (60, 100], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]


In [41]:
'''
print(cats.labels())
print(cats.levels())
'''
print(cats.codes)
print(cats.categories)
pd.value_counts(cats)

[0 0 0 1 0 0 2 3 3 2 2 1]
IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')


(18, 25]     5
(35, 60]     3
(60, 100]    2
(25, 35]     2
dtype: int64

In [42]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [61, 100), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [43]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., Senior, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [46]:
data = np.random.rand(20)
print(data)
pd.cut(data, 4, precision=2)

[0.98987575 0.8168553  0.64447727 0.05200912 0.81189984 0.31772897
 0.95097833 0.50065354 0.82519333 0.91964042 0.37876573 0.17709446
 0.53823199 0.37343473 0.29750429 0.67091764 0.20163851 0.08736066
 0.640167   0.28609936]


[(0.76, 0.99], (0.76, 0.99], (0.52, 0.76], (0.051, 0.29], (0.76, 0.99], ..., (0.52, 0.76], (0.051, 0.29], (0.051, 0.29], (0.52, 0.76], (0.051, 0.29]]
Length: 20
Categories (4, interval[float64]): [(0.051, 0.29] < (0.29, 0.52] < (0.52, 0.76] < (0.76, 0.99]]

In [47]:
data = np.random.randn(1000)
cats = pd.qcut(data, 5)

In [48]:
np.random.seed(12345)
data = DataFrame(np.random.randn(1000, 4))
data.shape

(1000, 4)

In [51]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [54]:
col = data[3]
col[np.abs(col) > 3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [58]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

In [61]:
df = DataFrame(np.arange(5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5)
print(sampler)

[1 3 0 2 4]


In [62]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11
4  16  17  18  19

In [67]:
bag = np.array([5, 7, -1, 6, 4])
sampler = np.random.randint(0, len(bag), size=10)
print(sampler)
draws = bag.take(sampler)
print(draws)

[2 2 2 2 4 3 1 0 2 1]
[-1 -1 -1 -1  4  6  7  5 -1  7]


In [68]:
df = DataFrame({'key' : ['b', 'b', 'a', 'c', 'a', 'b'],
                'data1' : range(6)})

In [69]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [72]:
dummies = pd.get_dummies(df['key'], prefix='key')
# error : df['data1'].join(dummies)
df[['data1']].join(dummies)

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [75]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('movies.dat', sep='::', header=None, names=mnames)
movies.head(6)

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller

In [79]:
genre_iter = (set(x.split('|')) for x in movies.genres)
# list(genre_iter)

In [80]:
genres = sorted(set.union(*genre_iter))
print(genres)

['Action', 'Adventure', 'Animation', "Children's", 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']


In [84]:
dummies = DataFrame(np.zeros((len(movies), len(genres))), columns=genres)
for i, temp_genre in enumerate(movies.genres):
    dummies.loc[i, temp_genre.split('|')] = 1
# dummies.head(10)

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0     0.0        0.0        1.0         1.0     1.0    0.0          0.0   
1     0.0        1.0        0.0         1.0     0.0    0.0          0.0   
2     0.0        0.0        0.0         0.0     1.0    0.0          0.0   
3     0.0        0.0        0.0         0.0     1.0    0.0          0.0   
4     0.0        0.0        0.0         0.0     1.0    0.0          0.0   
5     1.0        0.0        0.0         0.0     0.0    1.0          0.0   
6     0.0        0.0        0.0         0.0     1.0    0.0          0.0   
7     0.0        1.0        0.0         1.0     0.0    0.0          0.0   
8     1.0        0.0        0.0         0.0     0.0    0.0          0.0   
9     1.0        1.0        0.0         0.0     0.0    0.0          0.0   

   Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
0    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
1    0.0      1.0        0.0     0.0      0.0      0.0      0.0     0.0   
2    0.0      0.0        0.0     0.0      0.0      0.0      1.0     0.0   
3    1.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
4    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
5    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
6    0.0      0.0        0.0     0.0      0.0      0.0      1.0     0.0   
7    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
8    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
9    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   

   Thriller  War  Western  
0       0.0  0.0      0.0  
1       0.0  0.0      0.0  
2       0.0  0.0      0.0  
3       0.0  0.0      0.0  
4       0.0  0.0      0.0  
5       1.0  0.0      0.0  
6       0.0  0.0      0.0  
7       0.0  0.0      0.0  
8       0.0  0.0      0.0  
9       1.0  0.0      0.0

In [88]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
print(movies_windic.columns)
movies_windic.iloc[0]

Index(['movie_id', 'title', 'genres', 'Genre_Action', 'Genre_Adventure',
       'Genre_Animation', 'Genre_Children's', 'Genre_Comedy', 'Genre_Crime',
       'Genre_Documentary', 'Genre_Drama', 'Genre_Fantasy', 'Genre_Film-Noir',
       'Genre_Horror', 'Genre_Musical', 'Genre_Mystery', 'Genre_Romance',
       'Genre_Sci-Fi', 'Genre_Thriller', 'Genre_War', 'Genre_Western'],
      dtype='object')


movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [90]:
values = np.random.rand(10)
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           1           0           0
1           1           0           0           0           0
2           0           0           1           0           0
3           1           0           0           0           0
4           0           0           0           1           0
5           0           0           0           1           0
6           0           0           0           0           1
7           0           0           0           0           1
8           0           0           0           0           1
9           1           0           0           0           0

In [2]:
val = 'a, b,   guido'
val.split(',')

['a', ' b', '   guido']

In [92]:
pieces = [x.strip() for x in val.split(',')]
print(pieces)

['a', 'b', 'guido']


In [93]:
'::'.join(pieces)

'a::b::guido'

In [95]:
'_'.join(['a', 'b', 'c'])

'a_b_c'

In [6]:
print(val)
print('guido' in val)
print(val.index(','))
print(val.find(';'))

a, b,   guido
True
1
-1


In [2]:
import re

text = "foo   bar\t baz   \tqux"
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [10]:
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [11]:
regex.findall(text)

['   ', '\t ', '   \t']

In [7]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

pattern = r'([A-Z0-9_.]+)@([A-Z0-9_]+)\.([A-Z]{2,4})'
# the regex is not okay

regex = re.compile(pattern, flags=re.IGNORECASE)

print(text)
print(regex.findall(text))
print(regex.search(text))

Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com

[('dave', 'google', 'com'), ('steve', 'gmail', 'com'), ('rob', 'gmail', 'com'), ('ryan', 'yahoo', 'com')]
<re.Match object; span=(5, 20), match='dave@google.com'>


In [9]:
m = regex.match('hdy@bjmu.edu.cn')
print(m)
m.groups()

<re.Match object; span=(0, 12), match='hdy@bjmu.edu'>


('hdy', 'bjmu', 'edu')