# 数据规整化

In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [28]:
df1 = DataFrame({'key' : ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1' : range(7)})
df2 = DataFrame({'key' : ['a', 'b', 'd'], 'data2' : range(3)})

pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [ ]:
df3 = DataFrame({'lkey' : ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1' : range(7)})
df4 = DataFrame({'rkey' : ['a', 'b', 'd'], 'data2' : range(3)})

pd.merge(df3, df4, left_on='lkey', right_on='rkey')

In [ ]:
print(pd.merge(df1, df2, how='left'))
print(pd.merge(df1, df2, how='right'))
print(pd.merge(df1, df2, how='outer'))

In [ ]:
left = DataFrame({'key1' : ['foo', 'foo', 'bar'],
                  'key2' : ['one', 'two', 'one'],
                  'lval' : [1, 2, 3]})
right = DataFrame({'key1' : ['foo', 'foo', 'bar', 'bar'],
                   'key2' : ['one', 'one', 'one', 'two'],
                   'lval' : [4, 5, 6, 7]})

pd.merge(left, right, on='key1', how='outer', suffixes=('_left', '_right'))

In [ ]:
left_df = DataFrame([[1., 2.], [3., 4.], [5., 6.]], index=['a', 
'c', 'e'], columns=['Ohio', 'Nevada'])
right_df = DataFrame([[7., 8.], [9., 10.], [11., 12.], [13., 14.]], index=['b', 'c', 'd', 'e'], columns=['Missouri', 'Alabama'])

pd.merge(left_df, right_df, how='outer', left_index=True, right_index=True)

In [ ]:
print(left_df.join(right_df, how='right'))
print(left_df.join(right_df, how='left'))

In [35]:
arr = np.arange(12).reshape((3, 4))
print(np.concatenate([arr, arr], axis=0))
print(np.concatenate([arr, arr], axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [37]:
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['f', 'g'])

joint_s = pd.concat([s1, s2, s3])
type(joint_s)

pandas.core.series.Series

In [39]:
joint_s = pd.concat([s1, s2, s3], axis=1)
print(type(joint_s))
print(joint_s)

<class 'pandas.core.frame.DataFrame'>
     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0


In [46]:
result1 = pd.concat([s1, s2, s3], keys=['one', 'two', 'three'])
print(result1)
type(result1.unstack())

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64


pandas.core.frame.DataFrame

In [48]:
result2 = pd.concat([s1, s2, s3], keys=['one', 'two', 'three'], axis=1)
print(result2)

   one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0


In [50]:
df1 = DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])
print(pd.concat([df1, df2]))
print(pd.concat([df1, df2], ignore_index=True))

          a         b         c         d
0 -0.397156  1.594142  0.827900  1.319840
1 -0.349130 -1.083904  0.211642 -0.263606
2  0.810517 -0.707759 -0.461879 -0.147731
0 -0.037172 -0.466378       NaN -0.451507
1 -0.410540 -0.350071       NaN  1.360973
          a         b         c         d
0 -0.397156  1.594142  0.827900  1.319840
1 -0.349130 -1.083904  0.211642 -0.263606
2  0.810517 -0.707759 -0.461879 -0.147731
3 -0.037172 -0.466378       NaN -0.451507
4 -0.410540 -0.350071       NaN  1.360973


In [51]:
df1 = DataFrame({'a' : [1, np.nan, 5., np.nan],
                 'b' : [np.nan, 2., np.nan, 6.],
                 'c' : range(2, 18, 4)})

df2 = DataFrame({'a' : [5., 4., np.nan, 3., 7.],
                 'b' : [np.nan, 3., 4., 6., 8.]})

df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [2]:
data = DataFrame(np.arange(6).reshape((2, 3)), index=pd.Index(['Ohio', 'Colorado'], name='state'), columns=pd.Index(['one', 'two', 'three'], name='number'))
print(data)

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5


In [5]:
result = data.stack()
print(data.stack())
print(data.stack().unstack())

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64
number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5


In [9]:
print(result.unstack(0))
print(result.unstack(1))
print(result.unstack('state'))

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5
number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5
state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5


In [11]:
s1 = Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s2 = Series([4, 5, 6], index=['c', 'd', 'e'])
data2 = pd.concat([s1, s2], keys=['one', 'two'])
print(data2)

data2_2 = pd.concat([s1, s2], axis=1, keys=['one', 'two'])
print(data2_2)

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64
   one  two
a  0.0  NaN
b  1.0  NaN
c  2.0  4.0
d  3.0  5.0
e  NaN  6.0


In [16]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [18]:
df = DataFrame({'left' : result, 'right' : result + 5}, columns=pd.Index(['left', 'right'], name='side'))
print(df)

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10


In [19]:
df.unstack('state').stack('side')

state         Colorado  Ohio
number side                 
one    left          3     0
       right         8     5
two    left          4     1
       right         9     6
three  left          5     2
       right        10     7

In [60]:
time_p1 = list(np.repeat(pd.Timestamp('1959-03-31 00:00:00'), 3))
time_p2 = list(np.repeat(pd.Timestamp('1959-06-30 00:00:00'), 3))

print(np.append(time_p1, time_p2))

ldata = DataFrame({'date' : np.append(time_p1, time_p2), 'item' : (['realgdp', 'infl', 'unemp'] * 2), 'value' : [2710.349, 0.000, 5.800, 2778.801, 2.340, 5.100]})

print(ldata)

[Timestamp('1959-03-31 00:00:00') Timestamp('1959-03-31 00:00:00')
 Timestamp('1959-03-31 00:00:00') Timestamp('1959-06-30 00:00:00')
 Timestamp('1959-06-30 00:00:00') Timestamp('1959-06-30 00:00:00')]
        date     item     value
0 1959-03-31  realgdp  2710.349
1 1959-03-31     infl     0.000
2 1959-03-31    unemp     5.800
3 1959-06-30  realgdp  2778.801
4 1959-06-30     infl     2.340
5 1959-06-30    unemp     5.100


In [66]:
# pivot wider
print(type(ldata))
pivoted = ldata.pivot('date', 'item', 'value')


DatetimeIndex(['1959-03-31', '1959-06-30'], dtype='datetime64[ns]', name='date', freq=None)

In [71]:
ldata['value2'] = np.random.randn(len(ldata))
print(len(ldata))
print(ldata.shape[1])
print(ldata)

6
4
        date     item     value    value2
0 1959-03-31  realgdp  2710.349 -0.385069
1 1959-03-31     infl     0.000  0.968437
2 1959-03-31    unemp     5.800 -1.899621
3 1959-06-30  realgdp  2778.801 -0.285930
4 1959-06-30     infl     2.340 -0.475144
5 1959-06-30    unemp     5.100 -1.292779


In [76]:
print(ldata.pivot('date', 'item', 'value'))
pivoted = ldata.pivot('date', 'item')

print(pivoted['value2', 'infl'])

item        infl   realgdp  unemp
date                             
1959-03-31  0.00  2710.349    5.8
1959-06-30  2.34  2778.801    5.1
date
1959-03-31    0.968437
1959-06-30   -0.475144
Name: (value2, infl), dtype: float64


In [80]:
print(ldata)
ldata.set_index(['date', 'item']).unstack('item')
ldata.set_index(['date', 'item']).unstack('item').value2

        date     item     value    value2
0 1959-03-31  realgdp  2710.349 -0.385069
1 1959-03-31     infl     0.000  0.968437
2 1959-03-31    unemp     5.800 -1.899621
3 1959-06-30  realgdp  2778.801 -0.285930
4 1959-06-30     infl     2.340 -0.475144
5 1959-06-30    unemp     5.100 -1.292779


item            infl   realgdp     unemp
date                                    
1959-03-31  0.968437 -0.385069 -1.899621
1959-06-30 -0.475144 -0.285930 -1.292779