# Chapter 5 of Python for Data Analysis

In [15]:
from pandas import Series, DataFrame
import numpy as np
import pandas as pd

In [3]:
obj = Series([4, 7, -5, 3])
print(obj.values)
print(obj.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [10]:
obj2 = Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'd'])
print(obj2['d'])
print(type(obj2.values))
print(type(obj2.index))
print(type(obj2))

d    4
d    5
dtype: int64
<class 'numpy.ndarray'>
<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.series.Series'>


In [17]:
obj3 = {'a' : 1, 'b' : 2, 'c' : 3}
obj3 = Series(obj3)
'a' in obj3 # True
1 in obj3 # False
np.in1d(1, obj3.values)

array([ True])

In [21]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}
obj5 = Series(sdata)
obj5 = Series(obj5, index=['Ohio', 'Texas', 'Bejing'])
print(obj5)
pd.isna(obj5).any()

Ohio      35000.0
Texas     71000.0
Bejing        NaN
dtype: float64


True

In [25]:
obj5.name = 'population'
obj5.index.name = 'city'
print(obj5)

city
Ohio      35000.0
Texas     71000.0
Bejing        NaN
Name: population, dtype: float64


In [32]:
test_df = {'A' : [1, 2, 3],
           'B' : [4, 6, 8],
           'C' : [5, 7, 99]}
test_df = DataFrame(test_df, index=['Beijing', 'Shanghai', 'Chongqing'])
print(test_df)

           A  B   C
Beijing    1  4   5
Shanghai   2  6   7
Chongqing  3  8  99


In [43]:
test_series = test_df.A
print(test_series)

# test_df.ix['Beijing']    discarded
print(test_df.loc['Beijing', :])
print(test_df.loc['Beijing',])
type(test_df.loc['Beijing', ['A', 'C']]) # after using .loc, it has become a Series
type(test_df.loc[['Beijing', 'Chongqing'], ['A', 'C']]) # DataFrame

Beijing      1
Shanghai     2
Chongqing    3
Name: A, dtype: int64
A    1
B    4
C    5
Name: Beijing, dtype: int64
A    1
B    4
C    5
Name: Beijing, dtype: int64


pandas.core.frame.DataFrame

In [50]:
obj6 = {'A' : {'Beijing':1, 'Shanghai':2, 'Chongqing':3}, 'B' : {'Beijing':4, 'Shanghai':6, 'Chongqing':8}}
obj6 = DataFrame(obj6)
print(obj6)
print(type(obj6.T))
print(obj6.values)

           A  B
Beijing    1  4
Shanghai   2  6
Chongqing  3  8
<class 'pandas.core.frame.DataFrame'>
[[1 4]
 [2 6]
 [3 8]]


In [65]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
print(obj2)
1 in obj2.index

obj2.index.unique()
pd.unique(obj2.index)
index.is_unique
index.unique
index.is_monotonic

0    1.5
1   -2.5
2    0.0
dtype: float64


True