# 数据规整化

In [34]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [28]:
df1 = DataFrame({'key' : ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1' : range(7)})
df2 = DataFrame({'key' : ['a', 'b', 'd'], 'data2' : range(3)})

pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [ ]:
df3 = DataFrame({'lkey' : ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1' : range(7)})
df4 = DataFrame({'rkey' : ['a', 'b', 'd'], 'data2' : range(3)})

pd.merge(df3, df4, left_on='lkey', right_on='rkey')

In [ ]:
print(pd.merge(df1, df2, how='left'))
print(pd.merge(df1, df2, how='right'))
print(pd.merge(df1, df2, how='outer'))

In [ ]:
left = DataFrame({'key1' : ['foo', 'foo', 'bar'],
                  'key2' : ['one', 'two', 'one'],
                  'lval' : [1, 2, 3]})
right = DataFrame({'key1' : ['foo', 'foo', 'bar', 'bar'],
                   'key2' : ['one', 'one', 'one', 'two'],
                   'lval' : [4, 5, 6, 7]})

pd.merge(left, right, on='key1', how='outer', suffixes=('_left', '_right'))

In [ ]:
left_df = DataFrame([[1., 2.], [3., 4.], [5., 6.]], index=['a', 
'c', 'e'], columns=['Ohio', 'Nevada'])
right_df = DataFrame([[7., 8.], [9., 10.], [11., 12.], [13., 14.]], index=['b', 'c', 'd', 'e'], columns=['Missouri', 'Alabama'])

pd.merge(left_df, right_df, how='outer', left_index=True, right_index=True)

In [ ]:
print(left_df.join(right_df, how='right'))
print(left_df.join(right_df, how='left'))

In [35]:
arr = np.arange(12).reshape((3, 4))
print(np.concatenate([arr, arr], axis=0))
print(np.concatenate([arr, arr], axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [37]:
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['f', 'g'])

joint_s = pd.concat([s1, s2, s3])
type(joint_s)

pandas.core.series.Series

In [39]:
joint_s = pd.concat([s1, s2, s3], axis=1)
print(type(joint_s))
print(joint_s)

<class 'pandas.core.frame.DataFrame'>
     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0


In [46]:
result1 = pd.concat([s1, s2, s3], keys=['one', 'two', 'three'])
print(result1)
type(result1.unstack())

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64


pandas.core.frame.DataFrame

In [48]:
result2 = pd.concat([s1, s2, s3], keys=['one', 'two', 'three'], axis=1)
print(result2)

   one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0


In [50]:
df1 = DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])
print(pd.concat([df1, df2]))
print(pd.concat([df1, df2], ignore_index=True))

          a         b         c         d
0 -0.397156  1.594142  0.827900  1.319840
1 -0.349130 -1.083904  0.211642 -0.263606
2  0.810517 -0.707759 -0.461879 -0.147731
0 -0.037172 -0.466378       NaN -0.451507
1 -0.410540 -0.350071       NaN  1.360973
          a         b         c         d
0 -0.397156  1.594142  0.827900  1.319840
1 -0.349130 -1.083904  0.211642 -0.263606
2  0.810517 -0.707759 -0.461879 -0.147731
3 -0.037172 -0.466378       NaN -0.451507
4 -0.410540 -0.350071       NaN  1.360973


In [51]:
df1 = DataFrame({'a' : [1, np.nan, 5., np.nan],
                 'b' : [np.nan, 2., np.nan, 6.],
                 'c' : range(2, 18, 4)})

df2 = DataFrame({'a' : [5., 4., np.nan, 3., 7.],
                 'b' : [np.nan, 3., 4., 6., 8.]})

df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN