# 读取数据集“MATRIX.TRAIN”

In [1]:
import numpy as np

In [6]:
fd = open('MATRIX.TRAIN', 'r')
hdr = fd.readline() # read the header of the file

rows, cols = [int(s) for s in fd.readline().strip().split()]

print(rows, cols)

'''
print(fd.readline()) # this is the third line of the file
'''

tokens = fd.readline().strip().split()
# print(tokens)

matrix = np.zeros((rows, cols))

Y = []
for i, line in enumerate(fd):
    nums = [int(x) for x in line.strip().split()] # ok
    Y.append(nums[0]) # ok, read the first element of a number line
    # print(nums)
    kv = np.array(nums[1:])
    # print(kv)
    k = np.cumsum(kv[:-1:2])
    # print(k)
    v = kv[1::2]
    matrix[i, k] = v

2144 1448
(2144, 1448)
[0. 0. 0. ... 0. 0. 0.]


In [16]:
'''
print(matrix.shape)
print(len(matrix[0]))
print(len(matrix[:, 0]))
print(matrix[:10, :10])
'''

(2144, 1448)
1448
2144
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]]
